apiVersion: apps/v1
kind: Deployment
metadata: 
  name: anky-deploy
  labels:
    app: tomcat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app : tomcat-app
  template:
    metadata: 
      name: anky-tomcat-pod
      labels:
        app: tomcat-app
    spec:
      containers:
      - name: anky-tomcat-cont
        image: ankyassasin/tomcat
        ports:
        - containerPort: 8080
